### ISSUE TITLE
Mount python dependencies via a symlink

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-webteam/generator-canonical-webteam#14]
Currently the dependencies is hardcoded to a `2.7/site-packages`.

For the upgrade to Python 3 we can change this to `3.6` which works but may cause some problem when we update to 3.7 or beyond.

A potential solution to look at, would be to mount a in a favoured location such as `/usr/local/lib/python3-current` and symlink that to the correct folder. Either:
- symlink `python3-current` to `./python3.6`
- symlink `python3.6/site-packages` to `../python3-current/site-packages`

**Comment by nottrobin** [comment]
I believe this is fixed in 9a2528c9538157fe0d08ed7e55878bd42542e9fd
