### ISSUE TITLE
Extract and expose key functions in a standard place outside of ./run

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/generator-canonical-webteam#25]
From the discussion at https://github.com/canonical-websites/conjure-up.io/pull/18#issuecomment-304252600:

> [The way Jekyll is run] just seemed to not match up to our previous work with having the logic visible and the ./run being an optional layer.
> For example the sass command is visible in the package.json but the jekyll command is hidden away.

The discussion should continue here, so we can find a way to expose the key functions for projects, e.g. `Jekyll`.

**Comment by nottrobin** [comment]
One proposal - maybe there isn't a better way? The way we encapsulate *build* functions in `package.json` so they can be run with `npm run build` (for those who don't want to use `./run`) still relies on `npm` as a local tool.

Similarly, the fact that our Jekyll projects are structured in the standard Jekyll format means they can be run with `jekyll serve`, `jekyll build` etc. Is this meaningfully more difficult or less transparent than the NPM projects? 

In both cases, someone familiar with that type of project should be able to run them in the way they would expect. Except perhaps that `jekyll build` won't build sass. Maybe we could make it do this itself somehow when run directly?

**Comment by nottrobin** [comment]
@WillMoggridge Do you think this needs further discussion or could I close it?

**Comment by deadlight** [comment]
@WillMoggridge bump. Please triage or close this one.
