### ISSUE TITLE
Add a run-jekyll script for projects which rely on Jekyll

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/generator-canonical-webteam#6]
How much of a future do Jekyll-based solutions have in our team? It would be nice if we could keep our stacks to purely Python and NodeJS. However, if it does have to include Ruby as well, in the long term, then we should create a standard and container for running Jekyll through Ruby Bundler, the same way as we have for Django (in #2).

If, however, we think Jekyll only has a limited life until we find a better solution, then it might be more expedient to simply create a zombie version of the Yarn image which includes Ruby and Jekyll hard-wired into it.

**Comment by anthonydillon** [comment]
No NodeJS. Our two stacks should be Python and Go. Flask and Hugo maybe?

**Comment by nottrobin** [comment]
@anthonydillon NodeJS is already in our stacks - basically every project has a package.json, for building Sass.

**Comment by nottrobin** [comment]
@anthonydillon And with regard to Ruby, we did decide a while ago that we'd standardise on Jekyll as our static site generator of choice. And we've now doubled-down on that by using GitHub Pages to host the [Vanilla examples](http://vanilla-framework.github.io/vanilla-framework/) (and now themes too?). So I'm leaning towards thinking we need to support Ruby+Jekyll in full, just like Python+Django.
