### ISSUE TITLE
Space in foldername breaks the run script

### ISSUE THREAD

**Issue by brlin-tw** [canonical-webteam/generator-canonical-webteam#67]
Just noticed this while trying to serve 'Snaps and snapcraft documentation' in my '$HOME/Workspace/Snaps and snapcraft documentation' folder.

```bash
# Generate the project name
if [[ -f ".docker-project" ]]; then
    project=$(cat .docker-project)
else
    directory=$(basename `pwd`)
    hash=$(pwd | ${md5_command} | cut -c1-8)
    project=canonical-webteam-${directory}-${hash}
    echo $project > .docker-project
fi
```

**Comment by nottrobin** [comment]
I think this was likely fixed in https://github.com/canonical-webteam/generator-canonical-webteam/pull/68. I'm closing this now, but @Lin-Buo-Ren let me know if your PR didn't fix this issue.

**Comment by brlin-tw** [comment]
The PR only fixes part of the issue and requires additional workaround by the user.  Unfortunately, I'm not using script now and no longer care whether this issue should be open or not so I'm fine with the status change.
