### ISSUE TITLE
No nice 404s

### ISSUE THREAD

**Issue by evilnick** [canonical-webteam/generator-canonical-webteam#72]
This seems to be an issue with all the docs sites:

E.g. try:
  https://docs.maas.io/2.3/en/not-a-page

What you should get:
 A nice 404 redirecting you to the index or something

What you actually get:
**Not Found**
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by evilnick** [comment]
just fyi @degville @pmatulis

**Comment by pmatulis** [comment]
@nottrobin Can we get some eyes on this?

**Comment by nottrobin** [comment]
This seems like an odd place for this issue to exist. As far as I'm aware, there's nothing in this generator project that impacts the actual content of documentation sites.

In any case, the way we write and host documentation is massively changing across the board - we're migrating MAAS and Juju docs - initially - into Discourse, and writing [a new app](https://github.com/canonical-websites/discourse-docs/) for docs websites with Discourse back-ends.

Documentation served using the existing documentation-builder model for docs.maas.io and others will quickly become legacy. Given that, we're not going to prioritise updating the 404 pages on those sites.

The best place at the moment, therefore, to consider writing a better 404 pages would be in the new application/plugin that will serve documentation pulled from Discourse (other than that, it will be a concern for each individual site to make sure they serve nice 404 pages).

I've created an issue over on the discourse-docs repository to track that: https://github.com/canonical-websites/discourse-docs/issues/5

I'll close this now.
